### ISSUE TITLE
Installation with pip misses BCARS phantom data

### ISSUE THREAD

**Issue by fmh96** [CCampJr/CRIkit2#86]
Generating the built-in Raman/BCARS numerical phantom doesn't work because the .csv files in crikit\datasets are missing. 
Solution: copy .csv files manually into the folder.

**Comment by CCampJr** [comment]
Awesome find: thank you.

Fixed in 100c7ce86ed8dd75b6bae4ee2f7642f3b579e44f

Pushing release 0.2.4 soon (github and PyPi [pip])

**Comment by CCampJr** [comment]
All done and updated
